# pytorch_lightning==2.1.3
seed_everything: true
trainer:
  precision: 32 # TODO
  logger:
    # WandbLogger(name=RUN_NAME, project=PROJECT_NAME)
    - class_path: pytorch_lightning.loggers.wandb.WandbLogger
      init_args:
        name: 05_per_img_loss
        project: align_ft_spair
        dir: "/home/user/Documents/projects/Metaworld/keyframes/align_ft_spair/logs"
        save_dir: "/home/user/Documents/projects/Metaworld/keyframes/align_ft_spair/logs"
  callbacks:
    # ModelCheckpoint(save_weights_only=True, mode="min", monitor="val_loss"),
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        save_weights_only: false
        mode: min
        monitor: val_loss
    # LearningRateMonitor("step"),
    - class_path: pytorch_lightning.callbacks.LearningRateMonitor
      init_args:
        logging_interval: epoch
    # - class_path: pytorch_lightning.callbacks.early_stopping.EarlyStopping
    #   init_args:
    #     monitor: val_loss
    #     patience: 300

  fast_dev_run: false
  max_epochs: 10000
  # on single RTX3090, log_every_n_steps should be around 50 / accumulate_grad_batches
  log_every_n_steps: 10
  enable_progress_bar: true  # roughly 10-11 iter/2
  accumulate_grad_batches: 2
  gradient_clip_val: 0.5
  # default_root_dir: /home/user/Documents/projects/Metaworld/keyframes/finetune_lightglue/logs
model:
  # model args
  dim: 2048

  # adamw optimizer
  optimizer_lr: 1.4e-4  # default of nanoGPT is 6e-4, minimum learning rate is 6e-5
  # milestones: [1000,1500,20000]
  # gamma: 0.1
  optimizer_warmup: 2500  # default of nanoGPT is 2000
  optimizer_max_iters: 2000000  # default of nanoGPT is 600'000
  optimizer_start_iter: 0
data:
  spair_data_folder: /media/user/ssd2t/datasets2/SPair-71k
  embds_folder_dino: /media/user/EXTREMESSD/datasets/SPair-71k/geo
  embds_folder_sd: /media/user/EXTREMESSD/datasets/SPair-71k/DiffusionFeatures60x60
  img_files_np_path_train: /home/user/Documents/projects/diffusion-features/experiments/ft_align/aeroplane_train_files_unique.npy
  img_files_np_path_eval: /home/user/Documents/projects/diffusion-features/experiments/ft_align/aeroplane_eval_files_unique.npy
  kpt_indices: [4, 5]
  category: aeroplane
  img_size: 960
  embd_size: 60
  pad: true
  batch_size: 16
  num_workers: 16
ckpt_path: